name: Auto JapanPost Re-delivery

on:
  schedule:
    # Chạy mỗi giờ (UTC)
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        echo "CHROME_BIN=$(which chromium-browser)" >> $GITHUB_ENV
        echo "CHROMEDRIVER=$(which chromedriver)"  >> $GITHUB_ENV

    - name: Run automation
      env:
        CASPIO_CLIENT_ID:     ${{ secrets.CASPIO_CLIENT_ID }}
        CASPIO_CLIENT_SECRET: ${{ secrets.CASPIO_CLIENT_SECRET }}
      run: |
        python -m jp_redelivery.cli
